<?php 
require "icreate.php";
require "output-regionais.php";
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-BR" lang="pt-BR">

	<head>
		<title>Gerador do Informe Primeira Leitura</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	</head>
	<body>
		<h1>Gerador do Primeira Leitura</h1>
		<p>Verifique se está tudo ok no preview abaixo. Para enviar, selecione o código no fim da página e cole dentro do Expresso Mail, não esqueça de clicar antes em <html>Ver código HTML</strong>.</p>
<table border="0" cellpadding="0" cellspacing="0" align="center" width="99.5%"><tr><td style="height:23px;background-color:#F0F3F4;"><p style="line-height: 23px;text-align: center;margin: 0;color: #6f8a91;font-size: 10px;font-family: arial, helvetica, sans-serif">Caso não consiga visualizar esta mensagem corretamente, <a style="color:#6f8a91 !important;" href="http://primeiraleitura.serpro.gov.br/">clique aqui.</a></p></td></tr></table><!-- END TOP BAR --><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top"><!-- HEADER --><tr><td> <table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" style="padding:55px 0;" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-header/"><td valign="top" width="150" align="center" colspan="3"><h1 style="margin: 0;padding: 0;line-height: 1.2"><img src="http://primeiraleitura.serpro.gov.br/img-newsletter/logo/" alt="Primeira Leitura" width="123px" height="107px" /></h1> <p style="font-size: 10px;line-height: 1.2;font-family: arial, helvetica, sans-serif">Boletim de Notícias Diário<br /><span style="color:#027598;line-height:1.8"><?php date("j/n/Y");?></span></p></td> <td width="65"></td><td valign="top" width="385"><?php destaque();?></td></table></td></tr><!-- END HEADER --><!-- CONTENT --><tr><td><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-content/"><!-- PUBLICITY --><?php publicidade();?><!-- END PUBLICITY --><tr><td width="200" valign="top"><?php coluna11(); coluna12(); coluna13();?></td><td width="200" valign="top"><?php coluna21(); coluna22(); coluna23();?></td><td width="200" valign="top"><?php coluna31();?></td></tr></table></td></tr><!-- END CONTENT --><!-- FOOTER --><tr><td width="600" style="padding:20px 0"> <img src="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-footer/" alt="" /><img style="padding-top:20px" src="http://primeiraleitura.serpro.gov.br/img-newsletter/assinatura/" alt="Serviço Federal de Processamento de Dados - SERPRO" /></td></tr><!-- END FOOTER --></table>

<h2>Nacional</h2>
<textarea readonly  style="border:1px solid #dedede;width:470px;min-height:500px;padding:20px;background:#fafafa;">
<table border="0" cellpadding="0" cellspacing="0" align="center" width="99.5%"><tr><td style="height:23px;background-color:#F0F3F4;"><p style="line-height: 23px;text-align: center;margin: 0;color: #6f8a91;font-size: 10px;font-family: arial, helvetica, sans-serif">Caso não consiga visualizar esta mensagem corretamente, <a style="color:#6f8a91 !important;" href="http://primeiraleitura.serpro.gov.br/">clique aqui.</a></p></td></tr></table><!-- END TOP BAR --><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top"><!-- HEADER --><tr><td> <table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" style="padding:55px 0;" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-header/"><td valign="top" width="150" align="center" colspan="3"><h1 style="margin: 0;padding: 0;line-height: 1.2"><img src="http://primeiraleitura.serpro.gov.br/img-newsletter/logo/" alt="Primeira Leitura" width="123px" height="107px" /></h1> <p style="font-size: 10px;line-height: 1.2;font-family: arial, helvetica, sans-serif">Boletim de Notícias Diário<br /><span style="color:#027598;line-height:1.8"><?php date("j/n/Y");?></span></p></td> <td width="65"></td><td valign="top" width="385"><?php destaque();?></td></table></td></tr><!-- END HEADER --><!-- CONTENT --><tr><td><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-content/"><!-- PUBLICITY --><?php publicidade();?><!-- END PUBLICITY --><tr><td width="200" valign="top"><?php coluna11(); coluna12(); coluna13();?></td><td width="200" valign="top"><?php coluna21(); coluna22(); coluna23();?></td><td width="200" valign="top"><?php coluna31();?></td> </tr></table></td></tr><!-- END CONTENT --><!-- FOOTER --><tr><td width="600" style="padding:20px 0"> <img src="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-footer/" alt="" /><img style="padding-top:20px" src="http://primeiraleitura.serpro.gov.br/img-newsletter/assinatura/" alt="Serviço Federal de Processamento de Dados - SERPRO" /></td></tr><!-- END FOOTER --></table>
</textarea>

<hr />
<h2>Regional Belém</h2>
<textarea readonly <?php if($_SESSION['checkblm'] == false){echo 'style="display:none;"';}else{};?> style="border:1px solid #dedede;width:470px;min-height:500px;padding:20px;background:#fafafa;">
<table border="0" cellpadding="0" cellspacing="0" align="center" width="99.5%"><tr><td style="height:23px;background-color:#F0F3F4;"><p style="line-height: 23px;text-align: center;margin: 0;color: #6f8a91;font-size: 10px;font-family: arial, helvetica, sans-serif">Caso não consiga visualizar esta mensagem corretamente, <a style="color:#6f8a91 !important;" href="http://primeiraleitura.serpro.gov.br/">clique aqui.</a></p></td></tr></table><!-- END TOP BAR --><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top"><!-- HEADER --><tr><td> <table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" style="padding:55px 0;" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-header/"><td valign="top" width="150" align="center" colspan="3"><h1 style="margin: 0;padding: 0;line-height: 1.2"><img src="http://primeiraleitura.serpro.gov.br/img-newsletter/logo/" alt="Primeira Leitura" width="123px" height="107px" /></h1> <p style="font-size: 10px;line-height: 1.2;font-family: arial, helvetica, sans-serif">Boletim de Notícias Diário<br /><span style="color:#027598;line-height:1.8"><?php date("j/n/Y");?></span></p></td> <td width="65"></td><td valign="top" width="385"><?php destaque();?></td></table></td></tr><!-- END HEADER --><!-- CONTENT --><tr><td><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-content/"><!-- PUBLICITY --><?php publicidade();?><!-- END PUBLICITY --><tr><td width="200" valign="top"><?php coluna11(); coluna12(); coluna13();?></td><td width="200" valign="top"><?php coluna21(); coluna22(); coluna23();?></td><td width="200" valign="top"><?php belem(); coluna31();?></td></tr></table></td></tr><!-- END CONTENT --><!-- FOOTER --><tr><td width="600" style="padding:20px 0"> <img src="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-footer/" alt="" /><img style="padding-top:20px" src="http://primeiraleitura.serpro.gov.br/img-newsletter/assinatura/" alt="Serviço Federal de Processamento de Dados - SERPRO" /></td></tr><!-- END FOOTER --></table>
</textarea>
<hr />
<h2>Regional Belo Horizonte</h2>
<textarea readonly <?php if($_SESSION['checkbhe'] == false){echo 'style="display:none;"';}else{};?> style="border:1px solid #dedede;width:470px;min-height:500px;padding:20px;background:#fafafa;">
<table border="0" cellpadding="0" cellspacing="0" align="center" width="99.5%"><tr><td style="height:23px;background-color:#F0F3F4;"><p style="line-height: 23px;text-align: center;margin: 0;color: #6f8a91;font-size: 10px;font-family: arial, helvetica, sans-serif">Caso não consiga visualizar esta mensagem corretamente, <a style="color:#6f8a91 !important;" href="http://primeiraleitura.serpro.gov.br/">clique aqui.</a></p></td></tr></table><!-- END TOP BAR --><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top"><!-- HEADER --><tr><td> <table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" style="padding:55px 0;" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-header/"><td valign="top" width="150" align="center" colspan="3"><h1 style="margin: 0;padding: 0;line-height: 1.2"><img src="http://primeiraleitura.serpro.gov.br/img-newsletter/logo/" alt="Primeira Leitura" width="123px" height="107px" /></h1> <p style="font-size: 10px;line-height: 1.2;font-family: arial, helvetica, sans-serif">Boletim de Notícias Diário<br /><span style="color:#027598;line-height:1.8"><?php date("j/n/Y");?></span></p></td> <td width="65"></td><td valign="top" width="385"><?php destaque();?></td></table></td></tr><!-- END HEADER --><!-- CONTENT --><tr><td><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-content/"><!-- PUBLICITY --><?php publicidade();?><!-- END PUBLICITY --><tr><td width="200" valign="top"><?php coluna11(); coluna12(); coluna13();?></td><td width="200" valign="top"><?php coluna21(); coluna22(); coluna23();?></td><td width="200" valign="top"><?php belzonte(); coluna31();?></td></tr></table></td></tr><!-- END CONTENT --><!-- FOOTER --><tr><td width="600" style="padding:20px 0"> <img src="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-footer/" alt="" /><img style="padding-top:20px" src="http://primeiraleitura.serpro.gov.br/img-newsletter/assinatura/" alt="Serviço Federal de Processamento de Dados - SERPRO" /></td></tr><!-- END FOOTER --></table>
</textarea>
<hr />
<h2>Regional Brasília</h2>
<textarea readonly <?php if($_SESSION['checkbsa'] == false){echo 'style="display:none;"';}else{};?> style="border:1px solid #dedede;width:470px;min-height:500px;padding:20px;background:#fafafa;">
<table border="0" cellpadding="0" cellspacing="0" align="center" width="99.5%"><tr><td style="height:23px;background-color:#F0F3F4;"><p style="line-height: 23px;text-align: center;margin: 0;color: #6f8a91;font-size: 10px;font-family: arial, helvetica, sans-serif">Caso não consiga visualizar esta mensagem corretamente, <a style="color:#6f8a91 !important;" href="http://primeiraleitura.serpro.gov.br/">clique aqui.</a></p></td></tr></table><!-- END TOP BAR --><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top"><!-- HEADER --><tr><td> <table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" style="padding:55px 0;" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-header/"><td valign="top" width="150" align="center" colspan="3"><h1 style="margin: 0;padding: 0;line-height: 1.2"><img src="http://primeiraleitura.serpro.gov.br/img-newsletter/logo/" alt="Primeira Leitura" width="123px" height="107px" /></h1> <p style="font-size: 10px;line-height: 1.2;font-family: arial, helvetica, sans-serif">Boletim de Notícias Diário<br /><span style="color:#027598;line-height:1.8"><?php date("j/n/Y");?></span></p></td> <td width="65"></td><td valign="top" width="385"><?php destaque();?></td></table></td></tr><!-- END HEADER --><!-- CONTENT --><tr><td><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-content/"><!-- PUBLICITY --><?php publicidade();?><!-- END PUBLICITY --><tr><td width="200" valign="top"><?php coluna11(); coluna12(); coluna13();?></td><td width="200" valign="top"><?php coluna21(); coluna22(); coluna23();?></td><td width="200" valign="top"><?php brasilia(); coluna31();?></td></tr></table></td></tr><!-- END CONTENT --><!-- FOOTER --><tr><td width="600" style="padding:20px 0"> <img src="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-footer/" alt="" /><img style="padding-top:20px" src="http://primeiraleitura.serpro.gov.br/img-newsletter/assinatura/" alt="Serviço Federal de Processamento de Dados - SERPRO" /></td></tr><!-- END FOOTER --></table>
</textarea>
<hr />
<h2>Regional Curitiba</h2>
<textarea readonly <?php if($_SESSION['checkcta'] == false){echo 'style="display:none;"';}else{};?> style="border:1px solid #dedede;width:470px;min-height:500px;padding:20px;background:#fafafa;">
<table border="0" cellpadding="0" cellspacing="0" align="center" width="99.5%"><tr><td style="height:23px;background-color:#F0F3F4;"><p style="line-height: 23px;text-align: center;margin: 0;color: #6f8a91;font-size: 10px;font-family: arial, helvetica, sans-serif">Caso não consiga visualizar esta mensagem corretamente, <a style="color:#6f8a91 !important;" href="http://primeiraleitura.serpro.gov.br/">clique aqui.</a></p></td></tr></table><!-- END TOP BAR --><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top"><!-- HEADER --><tr><td> <table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" style="padding:55px 0;" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-header/"><td valign="top" width="150" align="center" colspan="3"><h1 style="margin: 0;padding: 0;line-height: 1.2"><img src="http://primeiraleitura.serpro.gov.br/img-newsletter/logo/" alt="Primeira Leitura" width="123px" height="107px" /></h1> <p style="font-size: 10px;line-height: 1.2;font-family: arial, helvetica, sans-serif">Boletim de Notícias Diário<br /><span style="color:#027598;line-height:1.8"><?php date("j/n/Y");?></span></p></td> <td width="65"></td><td valign="top" width="385"><?php destaque();?></td></table></td></tr><!-- END HEADER --><!-- CONTENT --><tr><td><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-content/"><!-- PUBLICITY --><?php publicidade();?><!-- END PUBLICITY --><tr><td width="200" valign="top"><?php coluna11(); coluna12(); coluna13();?></td><td width="200" valign="top"><?php coluna21(); coluna22(); coluna23();?></td><td width="200" valign="top"><?php curitiba(); coluna31();?></td></tr></table></td></tr><!-- END CONTENT --><!-- FOOTER --><tr><td width="600" style="padding:20px 0"> <img src="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-footer/" alt="" /><img style="padding-top:20px" src="http://primeiraleitura.serpro.gov.br/img-newsletter/assinatura/" alt="Serviço Federal de Processamento de Dados - SERPRO" /></td></tr><!-- END FOOTER --></table>
</textarea>
<hr />
<h2>Regional Fortaleza</h2>
<textarea readonly <?php if($_SESSION['checkfla'] == false){echo 'style="display:none;"';}else{};?> style="border:1px solid #dedede;width:470px;min-height:500px;padding:20px;background:#fafafa;">
<table border="0" cellpadding="0" cellspacing="0" align="center" width="99.5%"><tr><td style="height:23px;background-color:#F0F3F4;"><p style="line-height: 23px;text-align: center;margin: 0;color: #6f8a91;font-size: 10px;font-family: arial, helvetica, sans-serif">Caso não consiga visualizar esta mensagem corretamente, <a style="color:#6f8a91 !important;" href="http://primeiraleitura.serpro.gov.br/">clique aqui.</a></p></td></tr></table><!-- END TOP BAR --><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top"><!-- HEADER --><tr><td> <table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" style="padding:55px 0;" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-header/"><td valign="top" width="150" align="center" colspan="3"><h1 style="margin: 0;padding: 0;line-height: 1.2"><img src="http://primeiraleitura.serpro.gov.br/img-newsletter/logo/" alt="Primeira Leitura" width="123px" height="107px" /></h1> <p style="font-size: 10px;line-height: 1.2;font-family: arial, helvetica, sans-serif">Boletim de Notícias Diário<br /><span style="color:#027598;line-height:1.8"><?php date("j/n/Y");?></span></p></td> <td width="65"></td><td valign="top" width="385"><?php destaque();?></td></table></td></tr><!-- END HEADER --><!-- CONTENT --><tr><td><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-content/"><!-- PUBLICITY --><?php publicidade();?><!-- END PUBLICITY --><tr><td width="200" valign="top"><?php coluna11(); coluna12(); coluna13();?></td><td width="200" valign="top"><?php coluna21(); coluna22(); coluna23();?></td><td width="200" valign="top"><?php fortaleza(); coluna31();?></td></tr></table></td></tr><!-- END CONTENT --><!-- FOOTER --><tr><td width="600" style="padding:20px 0"> <img src="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-footer/" alt="" /><img style="padding-top:20px" src="http://primeiraleitura.serpro.gov.br/img-newsletter/assinatura/" alt="Serviço Federal de Processamento de Dados - SERPRO" /></td></tr><!-- END FOOTER --></table>
</textarea>
<hr />
<h2>Regional Florianópolis</h2>
<textarea readonly <?php if($_SESSION['checkfns'] == false){echo 'style="display:none;"';}else{};?> style="border:1px solid #dedede;width:470px;min-height:500px;padding:20px;background:#fafafa;">
<table border="0" cellpadding="0" cellspacing="0" align="center" width="99.5%"><tr><td style="height:23px;background-color:#F0F3F4;"><p style="line-height: 23px;text-align: center;margin: 0;color: #6f8a91;font-size: 10px;font-family: arial, helvetica, sans-serif">Caso não consiga visualizar esta mensagem corretamente, <a style="color:#6f8a91 !important;" href="http://primeiraleitura.serpro.gov.br/">clique aqui.</a></p></td></tr></table><!-- END TOP BAR --><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top"><!-- HEADER --><tr><td> <table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" style="padding:55px 0;" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-header/"><td valign="top" width="150" align="center" colspan="3"><h1 style="margin: 0;padding: 0;line-height: 1.2"><img src="http://primeiraleitura.serpro.gov.br/img-newsletter/logo/" alt="Primeira Leitura" width="123px" height="107px" /></h1> <p style="font-size: 10px;line-height: 1.2;font-family: arial, helvetica, sans-serif">Boletim de Notícias Diário<br /><span style="color:#027598;line-height:1.8"><?php date("j/n/Y");?></span></p></td> <td width="65"></td><td valign="top" width="385"><?php destaque();?></td></table></td></tr><!-- END HEADER --><!-- CONTENT --><tr><td><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-content/"><!-- PUBLICITY --><?php publicidade();?><!-- END PUBLICITY --><tr><td width="200" valign="top"><?php coluna11(); coluna12(); coluna13();?></td><td width="200" valign="top"><?php coluna21(); coluna22(); coluna23();?></td><td width="200" valign="top"><?php floripa(); coluna31();?></td></tr></table></td></tr><!-- END CONTENT --><!-- FOOTER --><tr><td width="600" style="padding:20px 0"> <img src="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-footer/" alt="" /><img style="padding-top:20px" src="http://primeiraleitura.serpro.gov.br/img-newsletter/assinatura/" alt="Serviço Federal de Processamento de Dados - SERPRO" /></td></tr><!-- END FOOTER --></table>
</textarea>
<hr />
<h2>Regional Porto Alegre</h2>
<textarea readonly <?php if($_SESSION['checkpae'] == false){echo 'style="display:none;"';}else{};?> style="border:1px solid #dedede;width:470px;min-height:500px;padding:20px;background:#fafafa;">
<table border="0" cellpadding="0" cellspacing="0" align="center" width="99.5%"><tr><td style="height:23px;background-color:#F0F3F4;"><p style="line-height: 23px;text-align: center;margin: 0;color: #6f8a91;font-size: 10px;font-family: arial, helvetica, sans-serif">Caso não consiga visualizar esta mensagem corretamente, <a style="color:#6f8a91 !important;" href="http://primeiraleitura.serpro.gov.br/">clique aqui.</a></p></td></tr></table><!-- END TOP BAR --><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top"><!-- HEADER --><tr><td> <table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" style="padding:55px 0;" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-header/"><td valign="top" width="150" align="center" colspan="3"><h1 style="margin: 0;padding: 0;line-height: 1.2"><img src="http://primeiraleitura.serpro.gov.br/img-newsletter/logo/" alt="Primeira Leitura" width="123px" height="107px" /></h1> <p style="font-size: 10px;line-height: 1.2;font-family: arial, helvetica, sans-serif">Boletim de Notícias Diário<br /><span style="color:#027598;line-height:1.8"><?php date("j/n/Y");?></span></p></td> <td width="65"></td><td valign="top" width="385"><?php destaque();?></td></table></td></tr><!-- END HEADER --><!-- CONTENT --><tr><td><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-content/"><!-- PUBLICITY --><?php publicidade();?><!-- END PUBLICITY --><tr><td width="200" valign="top"><?php coluna11(); coluna12(); coluna13();?></td><td width="200" valign="top"><?php coluna21(); coluna22(); coluna23();?></td><td width="200" valign="top"><?php portoalegre(); coluna31();?></td></tr></table></td></tr><!-- END CONTENT --><!-- FOOTER --><tr><td width="600" style="padding:20px 0"> <img src="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-footer/" alt="" /><img style="padding-top:20px" src="http://primeiraleitura.serpro.gov.br/img-newsletter/assinatura/" alt="Serviço Federal de Processamento de Dados - SERPRO" /></td></tr><!-- END FOOTER --></table>
</textarea>
<hr />
<h2>Regional Recife</h2>
<textarea readonly <?php if($_SESSION['checkrce'] == false){echo 'style="display:none;"';}else{};?> style="border:1px solid #dedede;width:470px;min-height:500px;padding:20px;background:#fafafa;">
<table border="0" cellpadding="0" cellspacing="0" align="center" width="99.5%"><tr><td style="height:23px;background-color:#F0F3F4;"><p style="line-height: 23px;text-align: center;margin: 0;color: #6f8a91;font-size: 10px;font-family: arial, helvetica, sans-serif">Caso não consiga visualizar esta mensagem corretamente, <a style="color:#6f8a91 !important;" href="http://primeiraleitura.serpro.gov.br/">clique aqui.</a></p></td></tr></table><!-- END TOP BAR --><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top"><!-- HEADER --><tr><td> <table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" style="padding:55px 0;" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-header/"><td valign="top" width="150" align="center" colspan="3"><h1 style="margin: 0;padding: 0;line-height: 1.2"><img src="http://primeiraleitura.serpro.gov.br/img-newsletter/logo/" alt="Primeira Leitura" width="123px" height="107px" /></h1> <p style="font-size: 10px;line-height: 1.2;font-family: arial, helvetica, sans-serif">Boletim de Notícias Diário<br /><span style="color:#027598;line-height:1.8"><?php date("j/n/Y");?></span></p></td> <td width="65"></td><td valign="top" width="385"><?php destaque();?></td></table></td></tr><!-- END HEADER --><!-- CONTENT --><tr><td><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-content/"><!-- PUBLICITY --><?php publicidade();?><!-- END PUBLICITY --><tr><td width="200" valign="top"><?php coluna11(); coluna12(); coluna13();?></td><td width="200" valign="top"><?php coluna21(); coluna22(); coluna23();?></td><td width="200" valign="top"><?php recife(); coluna31();?></td></tr></table></td></tr><!-- END CONTENT --><!-- FOOTER --><tr><td width="600" style="padding:20px 0"> <img src="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-footer/" alt="" /><img style="padding-top:20px" src="http://primeiraleitura.serpro.gov.br/img-newsletter/assinatura/" alt="Serviço Federal de Processamento de Dados - SERPRO" /></td></tr><!-- END FOOTER --></table>
</textarea>
<hr />
<h2>Regional Rio de Janeiro</h2>
<textarea readonly <?php if($_SESSION['checkrjo'] == false){echo 'style="display:none;"';}else{};?> style="border:1px solid #dedede;width:470px;min-height:500px;padding:20px;background:#fafafa;">
<table border="0" cellpadding="0" cellspacing="0" align="center" width="99.5%"><tr><td style="height:23px;background-color:#F0F3F4;"><p style="line-height: 23px;text-align: center;margin: 0;color: #6f8a91;font-size: 10px;font-family: arial, helvetica, sans-serif">Caso não consiga visualizar esta mensagem corretamente, <a style="color:#6f8a91 !important;" href="http://primeiraleitura.serpro.gov.br/">clique aqui.</a></p></td></tr></table><!-- END TOP BAR --><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top"><!-- HEADER --><tr><td> <table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" style="padding:55px 0;" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-header/"><td valign="top" width="150" align="center" colspan="3"><h1 style="margin: 0;padding: 0;line-height: 1.2"><img src="http://primeiraleitura.serpro.gov.br/img-newsletter/logo/" alt="Primeira Leitura" width="123px" height="107px" /></h1> <p style="font-size: 10px;line-height: 1.2;font-family: arial, helvetica, sans-serif">Boletim de Notícias Diário<br /><span style="color:#027598;line-height:1.8"><?php date("j/n/Y");?></span></p></td> <td width="65"></td><td valign="top" width="385"><?php destaque();?></td></table></td></tr><!-- END HEADER --><!-- CONTENT --><tr><td><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-content/"><!-- PUBLICITY --><?php publicidade();?><!-- END PUBLICITY --><tr><td width="200" valign="top"><?php coluna11(); coluna12(); coluna13();?></td><td width="200" valign="top"><?php coluna21(); coluna22(); coluna23();?></td><td width="200" valign="top"><?php rio(); coluna31();?></td></tr></table></td></tr><!-- END CONTENT --><!-- FOOTER --><tr><td width="600" style="padding:20px 0"> <img src="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-footer/" alt="" /><img style="padding-top:20px" src="http://primeiraleitura.serpro.gov.br/img-newsletter/assinatura/" alt="Serviço Federal de Processamento de Dados - SERPRO" /></td></tr><!-- END FOOTER --></table>
</textarea>
<hr />
<h2>Regional Salvador</h2>
<textarea readonly <?php if($_SESSION['checksdr'] == false){echo 'style="display:none;"';}else{};?> style="border:1px solid #dedede;width:470px;min-height:500px;padding:20px;background:#fafafa;">
<table border="0" cellpadding="0" cellspacing="0" align="center" width="99.5%"><tr><td style="height:23px;background-color:#F0F3F4;"><p style="line-height: 23px;text-align: center;margin: 0;color: #6f8a91;font-size: 10px;font-family: arial, helvetica, sans-serif">Caso não consiga visualizar esta mensagem corretamente, <a style="color:#6f8a91 !important;" href="http://primeiraleitura.serpro.gov.br/">clique aqui.</a></p></td></tr></table><!-- END TOP BAR --><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top"><!-- HEADER --><tr><td> <table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" style="padding:55px 0;" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-header/"><td valign="top" width="150" align="center" colspan="3"><h1 style="margin: 0;padding: 0;line-height: 1.2"><img src="http://primeiraleitura.serpro.gov.br/img-newsletter/logo/" alt="Primeira Leitura" width="123px" height="107px" /></h1> <p style="font-size: 10px;line-height: 1.2;font-family: arial, helvetica, sans-serif">Boletim de Notícias Diário<br /><span style="color:#027598;line-height:1.8"><?php date("j/n/Y");?></span></p></td> <td width="65"></td><td valign="top" width="385"><?php destaque();?></td></table></td></tr><!-- END HEADER --><!-- CONTENT --><tr><td><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-content/"><!-- PUBLICITY --><?php publicidade();?><!-- END PUBLICITY --><tr><td width="200" valign="top"><?php coluna11(); coluna12(); coluna13();?></td><td width="200" valign="top"><?php coluna21(); coluna22(); coluna23();?></td><td width="200" valign="top"><?php salvador(); coluna31();?></td></tr></table></td></tr><!-- END CONTENT --><!-- FOOTER --><tr><td width="600" style="padding:20px 0"> <img src="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-footer/" alt="" /><img style="padding-top:20px" src="http://primeiraleitura.serpro.gov.br/img-newsletter/assinatura/" alt="Serviço Federal de Processamento de Dados - SERPRO" /></td></tr><!-- END FOOTER --></table>
</textarea>
<hr />
<h2>Regional São Paulo</h2>
<textarea readonly  <?php if($_SESSION['checkspo'] == false){echo 'style="display:none;"';}else{};?> style="border:1px solid #dedede;width:470px;min-height:500px;padding:20px;background:#fafafa;">
<table border="0" cellpadding="0" cellspacing="0" align="center" width="99.5%"><tr><td style="height:23px;background-color:#F0F3F4;"><p style="line-height: 23px;text-align: center;margin: 0;color: #6f8a91;font-size: 10px;font-family: arial, helvetica, sans-serif">Caso não consiga visualizar esta mensagem corretamente, <a style="color:#6f8a91 !important;" href="http://primeiraleitura.serpro.gov.br/">clique aqui.</a></p></td></tr></table><!-- END TOP BAR --><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top"><!-- HEADER --><tr><td> <table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" style="padding:55px 0;" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-header/"><td valign="top" width="150" align="center" colspan="3"><h1 style="margin: 0;padding: 0;line-height: 1.2"><img src="http://primeiraleitura.serpro.gov.br/img-newsletter/logo/" alt="Primeira Leitura" width="123px" height="107px" /></h1> <p style="font-size: 10px;line-height: 1.2;font-family: arial, helvetica, sans-serif">Boletim de Notícias Diário<br /><span style="color:#027598;line-height:1.8"><?php date("j/n/Y");?></span></p></td> <td width="65"></td><td valign="top" width="385"><?php destaque();?></td></table></td></tr><!-- END HEADER --><!-- CONTENT --><tr><td><table border="0" width="600" cellpadding="0" cellspacing="0" align="center" valign="top" background="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-content/"><!-- PUBLICITY --><?php publicidade();?><!-- END PUBLICITY --><tr><td width="200" valign="top"><?php coluna11(); coluna12(); coluna13();?></td><td width="200" valign="top"><?php coluna21(); coluna22(); coluna23();?></td><td width="200" valign="top"><?php sampa(); coluna31();?></td></tr></table></td></tr><!-- END CONTENT --><!-- FOOTER --><tr><td width="600" style="padding:20px 0"> <img src="http://primeiraleitura.serpro.gov.br/img-newsletter/bg-footer/" alt="" /><img style="padding-top:20px" src="http://primeiraleitura.serpro.gov.br/img-newsletter/assinatura/" alt="Serviço Federal de Processamento de Dados - SERPRO" /></td></tr><!-- END FOOTER --></table>
</textarea>
	</body>
</html>
<?php //session_destroy();?>